In [1]:
import pandas as pd 

df = pd.read_csv("../data/student-performance-factors.csv")

df.head()
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6529 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6517 non-null   str
 17  Distance_from_Home          6540 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [2]:
columns=["Teacher_Quality", "Parental_Education_Level", "Distance_from_Home"]

for column in columns:
    df[column]=df[column].fillna(df[column].mode()[0])

print(df[columns].isnull().sum())

Teacher_Quality             0
Parental_Education_Level    0
Distance_from_Home          0
dtype: int64

In [3]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [4]:
ordinal_columns = [
    "Parental_Involvement",
    "Access_to_Resources",
    "Motivation_Level",
    "Family_Income",
    "Teacher_Quality",
    "Peer_Influence",
    "Parental_Education_Level",
    "Distance_from_Home"
]

df[ordinal_columns].dtypes

for column in ordinal_columns:
    print(f"\n{column} :")
    print(df[column].unique())

Parental_Involvement :
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

Access_to_Resources :
<StringArray>
['High', 'Medium', 'Low']
Length: 3, dtype: str

Motivation_Level :
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

Family_Income :
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

Teacher_Quality :
<StringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

Peer_Influence :
<StringArray>
['Positive', 'Negative', 'Neutral']
Length: 3, dtype: str

Parental_Education_Level :
<StringArray>
['High School', 'College', 'Postgraduate']
Length: 3, dtype: str

Distance_from_Home :
<StringArray>
['Near', 'Moderate', 'Far']
Length: 3, dtype: str

In [5]:
categories = [
    ["Low", "Medium", "High"],  # Parental_Involvement
    ["Low", "Medium", "High"],  # Access_to_Resources
    ["Low", "Medium", "High"],  # Motivation_Level
    ["Low", "Medium", "High"],  # Family_Income
    ["Low", "Medium", "High"],  # Teacher_Quality
    ["Negative", "Neutral", "Positive"],  # Peer_Influence
    ["High School", "College", "Postgraduate"],  # Parental_Education_Level
    ["Near", "Moderate", "Far"]  # Distance_from_Home
]

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=categories)

df[ordinal_columns]=encoder.fit_transform(df[ordinal_columns])

df[ordinal_columns].head()
df[ordinal_columns].dtypes

Parental_Involvement        float64
Access_to_Resources         float64
Motivation_Level            float64
Family_Income               float64
Teacher_Quality             float64
Peer_Influence              float64
Parental_Education_Level    float64
Distance_from_Home          float64
dtype: object

In [6]:
one_hot_columns = [
    "Extracurricular_Activities",
    "Internet_Access",
    "School_Type",
    "Learning_Disabilities",
    "Gender"
]

df = pd.get_dummies(df, columns=one_hot_columns, dtype=int)

df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Internet_Access_No,Internet_Access_Yes,School_Type_Private,School_Type_Public,Learning_Disabilities_No,Learning_Disabilities_Yes,Gender_Female,Gender_Male
0,23,84,0.0,2.0,7,73,0.0,0,0.0,1.0,...,1,0,0,1,0,1,1,0,0,1
1,19,64,0.0,1.0,8,59,0.0,2,1.0,1.0,...,1,0,0,1,0,1,1,0,1,0
2,24,98,1.0,1.0,7,91,1.0,2,1.0,1.0,...,0,1,0,1,0,1,1,0,0,1
3,29,89,0.0,1.0,8,98,1.0,1,1.0,1.0,...,0,1,0,1,0,1,1,0,0,1
4,19,92,1.0,1.0,6,65,1.0,3,1.0,2.0,...,0,1,0,1,0,1,1,0,1,0